branch-defaults:
  main:
    environment: null
global:
  application_name: CommitHub - Backend
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Python 3.14 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
